### ISSUE TITLE
can't  install 0.5.2  - errors 

### ISSUE THREAD

**Issue by c3ph3us** [jbaiter/jpegtran-cffi#16]
```
pip --no-cache-dir install jpegtran-cffi
Collecting jpegtran-cffi
  Downloading jpegtran-cffi-0.5.2.tar.gz (138kB)
    100% |████████████████████████████████| 143kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    In file included from jpegtran/__pycache__/_cffi__xbfac4b5xcdb1023.c:210:0:
    src/epeg_private.h:71:17: warning: ‘_jpeg_init_source’ declared ‘static’ but never defined [-Wunused-function]
     METHODDEF(void) _jpeg_init_source(j_decompress_ptr cinfo);
                     ^
    src/epeg_private.h:72:20: warning: ‘_jpeg_fill_input_buffer’ declared ‘static’ but never defined [-Wunused-function]
     METHODDEF(boolean) _jpeg_fill_input_buffer(j_decompress_ptr cinfo);
                        ^
    src/epeg_private.h:73:17: warning: ‘_jpeg_skip_input_data’ declared ‘static’ but never defined [-Wunused-function]
     METHODDEF(void) _jpeg_skip_input_data(j_decompress_ptr cinfo, long num_bytes);
                     ^
    src/epeg_private.h:74:17: warning: ‘_jpeg_term_source’ declared ‘static’ but never defined [-Wunused-function]
     METHODDEF(void) _jpeg_term_source(j_decompress_ptr cinfo);
                     ^
    src/epeg_private.h:76:17: warning: ‘_jpeg_init_destination’ declared ‘static’ but never defined [-Wunused-function]
     METHODDEF(void) _jpeg_init_destination(j_compress_ptr cinfo);
                     ^
    src/epeg_private.h:77:20: warning: ‘_jpeg_empty_output_buffer’ declared ‘static’ but never defined [-Wunused-function]
     METHODDEF(boolean) _jpeg_empty_output_buffer (j_compress_ptr cinfo);
                        ^
    src/epeg_private.h:78:17: warning: ‘_jpeg_term_destination’ declared ‘static’ but never defined [-Wunused-function]
     METHODDEF(void) _jpeg_term_destination (j_compress_ptr cinfo);
                     ^
    src/epeg.c: In function ‘_epeg_trim’:
    src/epeg.c:1101:28: warning: variable ‘w’ set but not used [-Wunused-but-set-variable]
        int            y, a, b, w, h;
                                ^
    src/epeg.c: In function ‘_epeg_encode’:
    src/epeg.c:1204:52: warning: pointer targets in passing argument 3 of ‘jpeg_write_marker’ differ in signedness [-Wpointer-sign]
          jpeg_write_marker(&(im->out.jinfo), JPEG_COM, im->out.comment, strlen(im->out.comment));
                                                        ^
    In file included from src/epeg_private.h:14:0,
                     from src/epeg.c:2:
    /usr/include/jpeglib.h:969:14: note: expected ‘const JOCTET * {aka const unsigned char *}’ but argument is of type ‘char *’
     EXTERN(void) jpeg_write_marker (j_compress_ptr cinfo, int marker,
                  ^
    src/epeg.c:1213:58: warning: pointer targets in passing argument 3 of ‘jpeg_write_marker’ differ in signedness [-Wpointer-sign]
           jpeg_write_marker(&(im->out.jinfo), JPEG_APP0 + 7, buf, strlen(buf));
                                                              ^
    In file included from src/epeg_private.h:14:0,
                     from src/epeg.c:2:
    /usr/include/jpeglib.h:969:14: note: expected ‘const JOCTET * {aka const unsigned char *}’ but argument is of type ‘char *’
     EXTERN(void) jpeg_write_marker (j_compress_ptr cinfo, int marker,
                  ^
    src/epeg.c:1216:53: warning: pointer targets in passing argument 3 of ‘jpeg_write_marker’ differ in signedness [-Wpointer-sign]
      jpeg_write_marker(&(im->out.jinfo), JPEG_APP0 + 7, buf, strlen(buf));
                                                         ^
    In file included from src/epeg_private.h:14:0,
                     from src/epeg.c:2:
    /usr/include/jpeglib.h:969:14: note: expected ‘const JOCTET * {aka const unsigned char *}’ but argument is of type ‘char *’
     EXTERN(void) jpeg_write_marker (j_compress_ptr cinfo, int marker,
                  ^
    src/epeg.c:1218:53: warning: pointer targets in passing argument 3 of ‘jpeg_write_marker’ differ in signedness [-Wpointer-sign]
      jpeg_write_marker(&(im->out.jinfo), JPEG_APP0 + 7, buf, strlen(buf));
                                                         ^
    In file included from src/epeg_private.h:14:0,
                     from src/epeg.c:2:
    /usr/include/jpeglib.h:969:14: note: expected ‘const JOCTET * {aka const unsigned char *}’ but argument is of type ‘char *’
     EXTERN(void) jpeg_write_marker (j_compress_ptr cinfo, int marker,
                  ^
    src/epeg.c:1220:53: warning: pointer targets in passing argument 3 of ‘jpeg_write_marker’ differ in signedness [-Wpointer-sign]
      jpeg_write_marker(&(im->out.jinfo), JPEG_APP0 + 7, buf, strlen(buf));
                                                         ^
    In file included from src/epeg_private.h:14:0,
                     from src/epeg.c:2:
    /usr/include/jpeglib.h:969:14: note: expected ‘const JOCTET * {aka const unsigned char *}’ but argument is of type ‘char *’
     EXTERN(void) jpeg_write_marker (j_compress_ptr cinfo, int marker,
                  ^
    src/epeg.c:1222:53: warning: pointer targets in passing argument 3 of ‘jpeg_write_marker’ differ in signedness [-Wpointer-sign]
      jpeg_write_marker(&(im->out.jinfo), JPEG_APP0 + 7, buf, strlen(buf));
                                                         ^
    In file included from src/epeg_private.h:14:0,
                     from src/epeg.c:2:
    /usr/include/jpeglib.h:969:14: note: expected ‘const JOCTET * {aka const unsigned char *}’ but argument is of type ‘char *’
     EXTERN(void) jpeg_write_marker (j_compress_ptr cinfo, int marker,
                  ^
    jpegtran/__pycache__/_cffi__xb366312fxf3ca0677.c:209:27: fatal error: turbojpeg.h: Nie ma takiego pliku ani katalogu
    compilation terminated.
    src/transupp.c: In function ‘do_flip_h_no_crop’:
    src/transupp.c:137:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_h_scaled_size’
         (dstinfo->max_h_samp_factor * dstinfo->min_DCT_h_scaled_size);
                                              ^
    src/transupp.c: In function ‘do_flip_h’:
    src/transupp.c:203:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_h_scaled_size’
         (dstinfo->max_h_samp_factor * dstinfo->min_DCT_h_scaled_size);
                                              ^
    src/transupp.c: In function ‘do_flip_v’:
    src/transupp.c:268:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_v_scaled_size’
         (dstinfo->max_v_samp_factor * dstinfo->min_DCT_v_scaled_size);
                                              ^
    src/transupp.c: In function ‘do_rot_90’:
    src/transupp.c:396:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_h_scaled_size’
         (dstinfo->max_h_samp_factor * dstinfo->min_DCT_h_scaled_size);
                                              ^
    src/transupp.c: In function ‘do_rot_270’:
    src/transupp.c:477:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_v_scaled_size’
         (dstinfo->max_v_samp_factor * dstinfo->min_DCT_v_scaled_size);
                                              ^
    src/transupp.c: In function ‘do_rot_180’:
    src/transupp.c:545:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_h_scaled_size’
         (dstinfo->max_h_samp_factor * dstinfo->min_DCT_h_scaled_size);
                                              ^
    src/transupp.c:547:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_v_scaled_size’
         (dstinfo->max_v_samp_factor * dstinfo->min_DCT_v_scaled_size);
                                              ^
    src/transupp.c: In function ‘do_transverse’:
    src/transupp.c:656:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_h_scaled_size’
         (dstinfo->max_h_samp_factor * dstinfo->min_DCT_h_scaled_size);
                                              ^
    src/transupp.c:658:42: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_v_scaled_size’
         (dstinfo->max_v_samp_factor * dstinfo->min_DCT_v_scaled_size);
                                              ^
    src/transupp.c: In function ‘jtransform_request_workspace’:
    src/transupp.c:900:3: warning: implicit declaration of function ‘jpeg_core_output_dimensions’ [-Wimplicit-function-declaration]
       jpeg_core_output_dimensions(srcinfo);
       ^
    src/transupp.c:908:11: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_h_scaled_size’
        srcinfo->min_DCT_h_scaled_size,
               ^
    src/transupp.c:909:11: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_v_scaled_size’
        srcinfo->min_DCT_v_scaled_size,
               ^
    src/transupp.c:915:40: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_h_scaled_size’
        srcinfo->max_h_samp_factor * srcinfo->min_DCT_h_scaled_size,
                                            ^
    src/transupp.c:916:40: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_v_scaled_size’
        srcinfo->max_v_samp_factor * srcinfo->min_DCT_v_scaled_size,
                                            ^
    src/transupp.c:935:40: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_v_scaled_size’
           info->iMCU_sample_width = srcinfo->min_DCT_v_scaled_size;
                                            ^
    src/transupp.c:936:41: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_h_scaled_size’
           info->iMCU_sample_height = srcinfo->min_DCT_h_scaled_size;
                                             ^
    src/transupp.c:939:38: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_v_scaled_size’
      srcinfo->max_v_samp_factor * srcinfo->min_DCT_v_scaled_size;
                                          ^
    src/transupp.c:941:38: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_h_scaled_size’
      srcinfo->max_h_samp_factor * srcinfo->min_DCT_h_scaled_size;
                                          ^
    src/transupp.c:948:40: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_h_scaled_size’
           info->iMCU_sample_width = srcinfo->min_DCT_h_scaled_size;
                                            ^
    src/transupp.c:949:41: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_v_scaled_size’
           info->iMCU_sample_height = srcinfo->min_DCT_v_scaled_size;
                                             ^
    src/transupp.c:952:38: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_h_scaled_size’
      srcinfo->max_h_samp_factor * srcinfo->min_DCT_h_scaled_size;
                                          ^
    src/transupp.c:954:38: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_v_scaled_size’
      srcinfo->max_v_samp_factor * srcinfo->min_DCT_v_scaled_size;
                                          ^
    src/transupp.c: In function ‘transpose_critical_parameters’:
    src/transupp.c:1127:18: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_h_scaled_size’
       itemp = dstinfo->min_DCT_h_scaled_size;
                      ^
    src/transupp.c:1128:10: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_h_scaled_size’
       dstinfo->min_DCT_h_scaled_size = dstinfo->min_DCT_v_scaled_size;
              ^
    src/transupp.c:1128:43: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_v_scaled_size’
       dstinfo->min_DCT_h_scaled_size = dstinfo->min_DCT_v_scaled_size;
                                               ^
    src/transupp.c:1129:10: error: ‘struct jpeg_compress_struct’ has no member named ‘min_DCT_v_scaled_size’
       dstinfo->min_DCT_v_scaled_size = itemp;
              ^
    src/transupp.c: In function ‘jtransform_adjust_parameters’:
    src/transupp.c:1365:10: error: ‘struct jpeg_compress_struct’ has no member named ‘jpeg_width’
       dstinfo->jpeg_width = info->output_width;
              ^
    src/transupp.c:1366:10: error: ‘struct jpeg_compress_struct’ has no member named ‘jpeg_height’
       dstinfo->jpeg_height = info->output_height;
              ^
    src/transupp.c:1393:16: error: ‘struct jpeg_compress_struct’ has no member named ‘jpeg_width’
         if (dstinfo->jpeg_width != srcinfo->image_width ||
                    ^
    src/transupp.c:1394:9: error: ‘struct jpeg_compress_struct’ has no member named ‘jpeg_height’
      dstinfo->jpeg_height != srcinfo->image_height)
             ^
    src/transupp.c:1398:9: error: ‘struct jpeg_compress_struct’ has no member named ‘jpeg_width’
      dstinfo->jpeg_width, dstinfo->jpeg_height);
             ^
    src/transupp.c:1398:30: error: ‘struct jpeg_compress_struct’ has no member named ‘jpeg_height’
      dstinfo->jpeg_width, dstinfo->jpeg_height);
                                  ^
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gOd1tR/jpegtran-cffi/setup.py", line 5, in <module>
        import jpegtran.lib
      File "/tmp/pip-build-gOd1tR/jpegtran-cffi/jpegtran/__init__.py", line 1, in <module>
        from jpegtran.transform import JPEGImage
      File "/tmp/pip-build-gOd1tR/jpegtran-cffi/jpegtran/transform.py", line 5, in <module>
        import jpegtran.lib as lib
      File "/tmp/pip-build-gOd1tR/jpegtran-cffi/jpegtran/lib.py", line 208, in <module>
        libraries=["jpeg"])
      File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 450, in verify
        lib = self.verifier.load_library()
      File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 113, in load_library
        self._compile_module()
      File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 210, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 29, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose)
      File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 62, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by jbaiter** [comment]
Are you installing from PyPi or from the repository?
This might be related to a bad `libjpeg` version. I removed support for `libjpeg` back in February so that the bindings now only require `libturobjpeg` headers, you might want to give that a try.

**Comment by c3ph3us** [comment]
via $ pip --no-cache-dir install jpegtran-cffi

**Comment by jbaiter** [comment]
Can you try installing from the GitHub repository?

```
pip install git+https://github.com/jbaiter/jpegtran-cffi.git@master
```

**Comment by c3ph3us** [comment]
$  pip install git+https://github.com/jbaiter/jpegtran-cffi.git@master

Collecting git+https://github.com/jbaiter/jpegtran-cffi.git@master
  Cloning https://github.com/jbaiter/jpegtran-cffi.git (to master) to /tmp/pip-boiDuH-build
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.0 in /usr/lib/python2.7/dist-packages (from jpegtran-cffi===0.6a1)
Installing collected packages: jpegtran-cffi
  Running setup.py install for jpegtran-cffi ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-boiDuH-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Yu93EC-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'description_long'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/jpegtran
    copying jpegtran/jpegtran_build.py -> build/lib.linux-x86_64-2.7/jpegtran
    copying jpegtran/__init__.py -> build/lib.linux-x86_64-2.7/jpegtran
    copying jpegtran/transform.py -> build/lib.linux-x86_64-2.7/jpegtran
    copying jpegtran/lib.py -> build/lib.linux-x86_64-2.7/jpegtran
    copying jpegtran/jpegtran.cdef -> build/lib.linux-x86_64-2.7/jpegtran
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_jpegtran.c'
    creating build/temp.linux-x86_64-2.7
    building '_jpegtran' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_UNSIGNED_CHAR=1 -Isrc -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_jpegtran.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_jpegtran.o
    build/temp.linux-x86_64-2.7/_jpegtran.c:426:23: fatal error: turbojpeg.h: Nie ma takiego pliku ani katalogu
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-boiDuH-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Yu93EC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-boiDuH-build/

**Comment by jbaiter** [comment]
You're missing the turbojpeg header files, please install them before compiling (`apt-get install libturbojpeg0-dev`  in Debian/Ubuntu).

**Comment by cbm755** [comment]
Hopefully this nicely detailed report sends people here from search engines.

Thanks for reporting.
