### ISSUE TITLE
Can not install on windows

### ISSUE THREAD

**Issue by kosmos342** [jbaiter/jpegtran-cffi#18]
```
Collecting jpegtran-cffi
  Using cached jpegtran-cffi-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    _cffi__x7983a02axcdb1023.c
    src\epeg_private.h(5): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
    Traceback (most recent call last):
      File "C:\Python35\lib\distutils\_msvccompiler.py", line 382, in compile
        self.spawn(args)
      File "C:\Python35\lib\distutils\_msvccompiler.py", line 501, in spawn
        return super().spawn(cmd)
      File "C:\Python35\lib\distutils\ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "C:\Python35\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "C:\Python35\lib\distutils\spawn.py", line 81, in _spawn_nt
        "command %r failed with exit status %d" % (cmd, rc))
    distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "e:\soft-activity\api\win_build_env\lib\site-packages\cffi\ffiplatform.py", line 49, in _build
        dist.run_command('build_ext')
      File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "e:\soft-activity\api\win_build_env\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
        _build_ext.run(self)
      File "C:\Python35\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Python35\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\Python35\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "e:\soft-activity\api\win_build_env\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Python35\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "C:\Python35\lib\distutils\_msvccompiler.py", line 384, in compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-u1k_gd7v\jpegtran-cffi\setup.py", line 5, in <module>
        import jpegtran.lib
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-u1k_gd7v\jpegtran-cffi\jpegtran\__init__.py", line 1, in <module>
        from jpegtran.transform import JPEGImage
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-u1k_gd7v\jpegtran-cffi\jpegtran\transform.py", line 5, in <module>
        import jpegtran.lib as lib
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-u1k_gd7v\jpegtran-cffi\jpegtran\lib.py", line 39, in <module>
        libraries=["jpeg"])
      File "e:\soft-activity\api\win_build_env\lib\site-packages\cffi\api.py", line 438, in verify
        lib = self.verifier.load_library()
      File "e:\soft-activity\api\win_build_env\lib\site-packages\cffi\verifier.py", line 114, in load_library
        self._compile_module()
      File "e:\soft-activity\api\win_build_env\lib\site-packages\cffi\verifier.py", line 211, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "e:\soft-activity\api\win_build_env\lib\site-packages\cffi\ffiplatform.py", line 20, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "e:\soft-activity\api\win_build_env\lib\site-packages\cffi\ffiplatform.py", line 56, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.error.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1
\AppData\Local\Temp\pip-build-m0pmhtw8\jpegtran-cffi\

```

**Comment by jbaiter** [comment]
Looks like the `unistd.h` header file is missing on Windows :/ I currently don't have a Windows machine with a development environment at my disposal, so it's probably going to take a while before I can tackle this issue.
If you know C, you could modify the code to see if any of the approaches discussed in [this SO thread](http://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c) works and create a PR.

**Comment by kosmos342** [comment]
I removed including `unistd.h` and it works. It generate thumbnails. Can it affect somehow later?

**Comment by jbaiter** [comment]
Wow, you're right. The tests run flawlessly as well. Seems like I was a little too eager with the includes in t his case, thank you for finding that out!

**Comment by zwn** [comment]
Is there a release coming that includes this fix?
