### ISSUE TITLE
setup fails when cffi isn't installed already

### ISSUE THREAD

**Issue by neothemachine** [jbaiter/jpegtran-cffi#6]
A simple `pip install jpegtran-cffi` fails if cffi isn't installed already:

```
Downloading/unpacking jpegtran-cffi
  Downloading jpegtran-cffi-0.5.tar.gz (42kB): 42kB downloaded
  Running setup.py egg_info for package jpegtran-cffi
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_maik/jpegtran-cffi/setup.py", line 4, in <module>
        import jpegtran.lib
      File "jpegtran/__init__.py", line 1, in <module>
        from jpegtran.transform import JPEGImage
      File "jpegtran/transform.py", line 5, in <module>
        import jpegtran.lib as lib
      File "jpegtran/lib.py", line 9, in <module>
        from cffi import FFI
    ImportError: No module named cffi
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_maik/jpegtran-cffi/setup.py", line 4, in <module>

    import jpegtran.lib

  File "jpegtran/__init__.py", line 1, in <module>

    from jpegtran.transform import JPEGImage

  File "jpegtran/transform.py", line 5, in <module>

    import jpegtran.lib as lib

  File "jpegtran/lib.py", line 9, in <module>

    from cffi import FFI

ImportError: No module named cffi
```

In the setup.py it is listed correctly as dependency but already at line 4 it tries to import jpegtran.lib which fails as it needs cffi.

**Comment by stefanor** [comment]
cffi 1.0's improved build system should solve this. https://cffi.readthedocs.org/en/latest/cdef.html
